- hosts: elk 
  remote_user: root
  vars_files:
    - ./vars/vars.yml
  tasks:
  - name: check packages
    package_facts:
      manager: auto
  - name: install haproxy
    shell: apt install -y haproxy && systemctl enable haproxy 
    when: "'haproxy' not in ansible_facts.packages"
  - name: copy haproxy.cfg
    template: src=./template/haproxy.j2 dest=/etc/haproxy/haproxy.cfg mode=0644
  - name: restart-haproxy
    shell: systemctl restart haproxy
  - name: install keepalived
    shell: apt install -y keepalived && systemctl enable keepalived
    when: "'keepalived' not in ansible_facts.packages"
  - name: copy keepalived
    template: src=./template/keepalived.j2 dest=/etc/keepalived/keepalived.conf mode=0644
  - name: restart keepalived
    shell: systemctl restart keepalived 
